//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BachHoaVeSau
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONDATs = new HashSet<CHITIETDONDAT>();
            this.GIOHANGs = new HashSet<GIOHANG>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<System.DateTime> NSX { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public string DONVITINH { get; set; }
        public Nullable<int> SLTONKHO { get; set; }
        public Nullable<int> MALSP { get; set; }
        public Nullable<bool> FLAG { get; set; }
        public Nullable<bool> DEAL { get; set; }
        public string HINHANH { get; set; }
    
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONDAT> CHITIETDONDATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
    }
}
